name: os_ulas_mobile
description: "Flutter application showing detailed information about Osmaniye Public Transportation."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Core Dependencies
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.1

  # Localization
  easy_localization: ^3.0.7+1

  # Map
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2

  # Permissions
  permission_handler: ^12.0.1

  # Router
  go_router: ^16.0.0

  # Utilities
  hive: ^2.2.3
  image_picker: ^1.1.2
  logger: ^2.6.0
  curved_navigation_bar: ^1.0.6
  
  # code gen
  gen:
    path: module/gen

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter
  very_good_analysis: ^9.0.0

  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo/os_ulas_app_logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/langs/
    - assets/app_logo/
    - assets/map_themes/
