name: os_ulas_admin_panel
description: "Flutter web project that provides management of Osmaniye Public Transportation mobile application."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Core Dependencies
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.1

  # Localization
  easy_localization: ^3.0.7+1

  # Utilities
  hive: ^2.2.3
  image_picker: ^1.1.2
  logger: ^2.6.0

  # UI
  fl_chart: ^1.0.0

  # code gen
  gen:
    path: module/gen

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/langs/
